### ISSUE TITLE
Add code for workaround for incident mapping tools to work with 10.3.1 testing

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/incident-import-tools#2]
Deliver a new version of public safety incident maps to resolve an issue with incident mapping tools provided. This new release resolves an issue found in 10.3.1 testing. 

https://github.com/ArcGIS/local-government-information-model/issues/56

@WalterPotts @allisonmuise @ScottOppmann FYI

Need to certify fix on:
10.2.2
10.3, 
10.3.1

Email has one line code change for workaround

**Comment by LindsayThomas** [comment]
Issue: 
On 10.3.1 only we get an ‘invalid expression’ error with one of our script when using Make Table View. 
•         This error is reproducible outside our script by running the tool from the UI. 
•         I cannot reproduce this error in 10.3 (multiple machines tested)
•         I can reproduce this on multiple installations of 10.3.1 (build 4958)
•         I cannot reproduce this error with a feature class as input. (only tested csv and fc)
•         If I provide an expression (optional parameter), the tool succeeds

Repro steps:
1)      Open ArcMap and search for the Make Table View tool.
2)      Open the tool UI and drag in/browse to any csv for the Input Table
3)      Leaving all other parameters as defaults, click OK.

In 10.3 the tool successfully creates the table; in 10.3.1 it fails with this message:

Executing: MakeTableView C:\Users\alli6394\Desktop\PublicSafetyIncidentMaps\Application\Application\SampleData\TestCSV.csv TestCSV_View # # "CALLID CALLID VISIBLE NONE;FULLADDR FULLADDR VISIBLE NONE;RESCITY RESCITY VISIBLE NONE;RESSTATE RESSTATE VISIBLE NONE;RESZIP5 RESZIP5 VISIBLE NONE;PRIORITY PRIORITY VISIBLE NONE"
Start Time: Tue Mar 31 09:04:07 2015
ERROR 000358: Invalid expression
Failed to execute (MakeTableView).
Failed at Tue Mar 31 09:04:07 2015 (Elapsed Time: 0.01 seconds)

@jmhauck Above is the issue. The workaround we need is ....

"To use Copy Rows first to convert the *.csv to a table and then use the table as input to Make Table View."

**Comment by LindsayThomas** [comment]
Checked into Master here
https://github.com/Esri/incident-import-tools/commit/9b3f2698f9d3402e9cce068f5807dac4914d2a7f

**Comment by LindsayThomas** [comment]
@allisonmuise Please review @jmhauck code changes and ensure they make sense in terms of the changes.

**Comment by allisonmuise** [comment]
@LindsayThomas I will do this as part of my testing.

**Comment by LindsayThomas** [comment]
@allisonmuise closing this based on your comments in issue #4
