### ISSUE TITLE
Certification of June 2015 Release

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/incident-import-tools#4]
@WalterPotts  Please Certify the Release Candidate version of the tool on the following versions (If this is all ready done then just check off the tested versions we have tested.)

- [x] 10.2.2
- [x] 10.3
- [x] 10.3.1

Please use the most recent version of Master Here 
https://github.com/Esri/incident-import-tools/tree/master

**Comment by WalterPotts** [comment]
Confirmed the scripts run without error on all versions listed above.

**Comment by LindsayThomas** [comment]
Need to confirm that this works on ArcGIS Server as well 

- [ ] 10.2.2 (Desktop with Server )
- [ ] 10.3  (Desktop with Server )
- [ ] 10.3.1 (Desktop with Server )

**Comment by allisonmuise** [comment]
Tested on all 3 versions of Server listed above. @jmhauck 's fix was successful, but service publishing failed in all cases using the release candidate and the currently released versions of the scripts. More testing and possibly dev work will be needed.

**Comment by allisonmuise** [comment]
server publishing is now working and tools are ready to ship

**Comment by LindsayThomas** [comment]
@allisonmuise What version of the tools passed testing?
Where the tools tested and passed successfully 
    10.2.2 (Desktop with Server )
    10.3 (Desktop with Server )
    10.3.1 (Desktop with Server )
?

**Comment by allisonmuise** [comment]
The same version I was testing before. I tested on 10.3.1.
