### ISSUE TITLE
Publishing Services from Script fails on ArcGIS for Server 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/incident-import-tools#5]
Service publishing fails on ArcGIS for Server (all versions) in all cases using the release candidate and the currently released versions of the scripts. 

Issue does not occur on AGOL. 

@allisonmuise Can you please provide more information on this issue?

**Comment by jmhauck** [comment]
My experience was the reverse of what is listed above. I had no issues as is with publishing to AGS. However, I would get an error when publishing to AGOL. I made a minor change to the AGOL side and they are both completing without error for me now. If you are still seeing an issue I will need some more details I guess.

**Comment by jmhauck** [comment]
Also I only looked at this on 10.3.1

**Comment by jmhauck** [comment]
@allisonmuise could I see an example .cfg that was used for testing the AGS side please?

**Comment by allisonmuise** [comment]
This is now non-repro, so closing

**Comment by LindsayThomas** [comment]
Note: the changes made for this issue were for the AGOL part of publishing the script which wasn't the original  and issue. This change has not been included in the July release. But is a positive change and should be included in the next release per discussion with John and Allison. 

(AGOL publishes fine without this issue as verified by LT and WP)
